In [39]:
# Linear Regression Model - Student_Performance

In [40]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv('Student_Performance.csv')

In [42]:
df.head(3)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0

In [43]:
df.shape

(10000, 6)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [45]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [46]:
# as machine understands only binary lang we need to convert this "Activitites" column into numeric values as YES - 1 and NO - 0

In [47]:
df['Extracurricular Activities'] = df['Extracurricular Activities'].replace({'Yes' : 1, 'No' : 0})

/tmp/ipykernel_1074/4018035254.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Extracurricular Activities'] = df['Extracurricular Activities'].replace({'Yes' : 1, 'No' : 0})

In [48]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [49]:
# In order to update any thing in data is called as Feature Engineering

In [50]:
# another method to replace it by map
# df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes' : 1, 'No' : 0})

In [51]:
# Now figuring out dependent and independent variable

In [52]:
# Separating Dependent and Independent Variables

In [53]:
X = df.drop(['Performance Index'] , axis = 1)  # axix = 1 - Columns  axis = 0 - rows
y = df['Performance Index']

In [54]:
X.head(5) # Capital X represents independent variables

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5

In [55]:
y.head(5)  # Small y  represents dependent variables

0    91.0
1    65.0
2    45.0
3    36.0
4    66.0
Name: Performance Index, dtype: float64

In [56]:
  # Dividing Data into train_test split which is in (70/30) & (80/20) ratio

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [58]:
from sklearn.linear_model import LinearRegression

In [59]:
model = LinearRegression()

In [60]:
model.fit(X_train, y_train)

LinearRegression()

In [61]:
y_pred = model.predict(X_test)

In [62]:
y_pred

array([54.71185392, 22.61551294, 47.90314471, ..., 16.79341955,
       63.34327368, 45.94262301])

In [63]:
# Evaluation Metrics MAE, MSE, RMSE, R2 Score for linear regression model

In [64]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error,r2_score

In [65]:
MAE = mean_absolute_error(y_test,y_pred)
MSE = mean_squared_error(y_test,y_pred)
RMSE = root_mean_squared_error(y_test,y_pred)

In [66]:
print("MAE : ",MAE)
print("MSE : ",MSE)
print("RMSE : ",RMSE)

MAE :  1.6111213463123044
MSE :  4.082628398521853
RMSE :  2.0205515085050054

In [67]:
R2 = r2_score(y_test,y_pred)

In [68]:
print("R2 Score : ", R2)

R2 Score :  0.9889832909573145

In [69]:
# Let's Predict The Output From Outer Inputs

In [70]:
df.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [85]:
student1 = np.array([[8,51,1,7,2]])

In [86]:
student1_prediction = model.predict(student1)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [87]:
student1_prediction

array([45.09519332])

In [88]:
import joblib
from google.colab import files


# Model ko Colab me save karne ke liye
joblib.dump(model, "model.pkl")

# Save kiye hue model ko wapas load karne ke liye
files.download("model.pkl")

In [75]:
df.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [76]:
X_train.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced'],
      dtype='object')

In [79]:
X.head(3)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2

In [82]:
y.head(3)

0    91.0
1    65.0
2    45.0
Name: Performance Index, dtype: float64